openapi: 3.0.0
info:
  description: A simple API for fitness tracking. Users can create workout plans based on their goals.
  version: "1.0.0"
  title: Fitness Planning API
  contact:
    email: mafonso4@my.bcit.ca
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /event_stats:
    get:
      operationId: app.get_events
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  "0001":
                    type: integer
                    description: Number of events with code 0001
                  "0002":
                    type: integer
                    description: Number of events with code 0002
                  "0003":
                    type: integer
                    description: Number of events with code 0003
                  "0004":
                    type: integer
                    description: Number of events with code 0004
